schema_version = "1.0.0"
id = "UnexpectedImporters"
version = "1.0.0"
name = "UnexpectedImporters"
tagline = "A set of importers for Blender"
maintainer = "Nicolas Predella <nicolas.predella@antek.it>"
type = "add-on"
website = "https://github.com/PredellaN/UnexpectedImporters"
blender_version_min = "4.3.0"
license = [
    "SPDX:GPL-3.0-or-later"
]
tags = ["Import-Export"]
platforms = [
    "windows-x64",
    "macos-arm64",
    "linux-x64"
]
wheels = [
    "wheels/pye57-0.4.17-cp311-cp311-macosx_11_0_arm64.whl",
    "wheels/pye57-0.4.17-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
    "wheels/pye57-0.4.17-cp311-cp311-win_amd64.whl",
    "wheels/pyquaternion-0.9.9-py3-none-any.whl",
]
copyright = [
  "2016-2024 PrusaSlicer, Prusa Research a.s., released under GNU AGPLv3"
]

[permissions]
files = "Import/export of configurations, creation of tempfiles"

[build]
paths_exclude_pattern = [
  "__pycache__/",
  "experimental/",
  "cache/",
]
